### ISSUE TITLE
Doesn't work on Kodi 17.0 Beta 1

### ISSUE THREAD

**Issue by SebJansen** [ddurdle/GDrive-for-KODI#93]

**Comment by ddurdle** [comment]
error log?

**Comment by ddurdle** [comment]
AttributeError: 'URLError' object has no attribute 'code'

**Comment by negroISO** [comment]
YMMV I've been using it on LibreElec LibreELEC (Krypton) v7.90.008 ALPHA containing Kodi v17.0-beta5 and it seems to be glorious. I didn't have a problem with previous betas. Is this topic closed due to how long it's been without reply?

**Comment by ddurdle** [comment]
The issue is still open.

**Comment by ddurdle** [comment]
Tested on BETA 7 and no issues encountered.  Closing.  If you encounter issues, update to the latest KODI 17 BETA.
